const ActionTypes = {
  START_GET_DATA: 'START_GET_DATA',
  DONE_GET_DATA: 'DONE_GET_DATA',
  MQTT_MESSAGE_ARRIVED: 'MQTT_MESSAGE_ARRIVED',
  SHOW_ALL_DEVICES: 'SHOW_ALL_DEVICES',
  FILTER_DEVICES_ONLINE: 'FILTER_DEVICES_ONLINE',
  FILTER_DEVICES_OFFLINE: 'FILTER_DEVICES_OFFLINE'
}

export default ActionTypes